In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os

# Any results you write to the current directory are saved as output.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")
df.iloc[:,1:] /= 255 #normalização dos valores
#df.sample(20)
df.head()


label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
1      0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
2      1     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
3      4     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
4      0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0

[5 rows x 785 columns]

In [4]:
y = df.iloc[:,:1] #o y será a priemria coluna
x = df.iloc[:,1:] #o x será todas as colunas exceto a coluna 1

In [10]:
print(x)

       pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
1         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
2         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
3         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
4         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
...       ...     ...     ...     ...  ...       ...       ...       ...       ...
41995     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41996     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41997     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41998     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41999     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0

[42

In [11]:
print(y)

       label
0          1
1          0
2          1
3          4
4          0
...      ...
41995      0
41996      1
41997      7
41998      6
41999      9

[42000 rows x 1 columns]


# Input data

In [13]:
from math import ceil

n = x.shape[0]
n_train = ceil(0.8 * n)
n_test = ceil(0.2 * n)

x_train = x[:n_train]
y_train = y[:n_train]

x_test = x[n_train:]
y_test = y[n_train:]

y_train = np.squeeze(y_train)
y_test = np.squeeze(y_test)

# Building the model and evaluating

In [14]:
from sklearn.neural_network import MLPClassifier

mlp_model = MLPClassifier(solver='adam', 
                          alpha=1e-5, 
                          hidden_layer_sizes=(1024, 128), 
                          random_state=1, 
                          max_iter=150)

print(mlp_model)

mlp_model.fit(x_train, y_train)  #executa o treinamento no modelo configurado.                  
pred_mlp =  mlp_model.predict(x_test) #executa o teste do modelo

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(1024, 128), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=150,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)


In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn import metrics

print("\n\nTesting using MLP")
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, pred_mlp))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, pred_mlp))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, pred_mlp))) 



Testing using MLP
Mean Absolute Error: 0.07964285714285714
Mean Squared Error: 0.4201190476190476
Root Mean Squared Error: 0.6481659105653795


In [16]:
print("\n\nMLP")
print("--- confusion_matrix ---")
print(confusion_matrix(y_test, pred_mlp))  
print("\n--- classification report ---")
print(classification_report(y_test, pred_mlp))  
print("\nmodel accuracy: ", accuracy_score(y_test, pred_mlp))



MLP
--- confusion_matrix ---
[[845   0   1   0   0   0   4   1   1   0]
 [  0 940   1   0   1   0   1   2   5   0]
 [  3   0 785   4   0   0   2   3   2   2]
 [  2   3   4 858   0   5   0   2   4   4]
 [  0   4   0   0 794   1   5   0   1   6]
 [  3   2   1   3   2 724   3   0   5   4]
 [  2   2   1   0   2   1 823   0   0   0]
 [  0   2   3   2   0   2   0 870   2   3]
 [  1   7   0   2   2   4   1   0 783   2]
 [  5   2   1   4   8   1   0   1   3 815]]

--- classification report ---
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       852
           1       0.98      0.99      0.98       950
           2       0.98      0.98      0.98       801
           3       0.98      0.97      0.98       882
           4       0.98      0.98      0.98       811
           5       0.98      0.97      0.98       747
           6       0.98      0.99      0.99       831
           7       0.99      0.98      0.99       884
           8       0

# Recognizing numbers (or not)

In [21]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/test.csv")
df.iloc[:,1:] /= 255
df.head()

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0       0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
1       0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
2       0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
3       0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
4       0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0

[5 rows x 784 columns]

In [18]:
test = df.values
test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
preds =  mlp_model.predict(test)

In [22]:
index = df.index + 1
d = {"ImageId" : index, "Label" : preds}
df_out = pd.DataFrame(data=d)
df_out.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3

In [24]:
df_out.to_csv("/content/drive/MyDrive/Colab Notebooks/rec_numbers.csv", index=False)